//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideTracker.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RideTracker.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Alert_No {
            get {
                return ResourceManager.GetString("Alert_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Alert_Yes {
            get {
                return ResourceManager.GetString("Alert_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Error_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Error_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Group.
        /// </summary>
        internal static string Groups_CreateNew {
            get {
                return ResourceManager.GetString("Groups_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Groups_DeleteButtonTitle {
            get {
                return ResourceManager.GetString("Groups_DeleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of vehicles.
        /// </summary>
        internal static string Groups_DetailsPageTitle {
            get {
                return ResourceManager.GetString("Groups_DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string Groups_GroupNamePlaceholder {
            get {
                return ResourceManager.GetString("Groups_GroupNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have an invite code.
        /// </summary>
        internal static string Groups_IHaveCode {
            get {
                return ResourceManager.GetString("Groups_IHaveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite an Employee.
        /// </summary>
        internal static string Groups_InviteButtonTitle {
            get {
                return ResourceManager.GetString("Groups_InviteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Current.
        /// </summary>
        internal static string Groups_MakeCurrent {
            get {
                return ResourceManager.GetString("Groups_MakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an invite code press &quot;I have an invite code button&quot;.
        /// </summary>
        internal static string Groups_NoGroupsDescription {
            get {
                return ResourceManager.GetString("Groups_NoGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups_PageTitle {
            get {
                return ResourceManager.GetString("Groups_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History_DaysSummaryPageTitle {
            get {
                return ResourceManager.GetString("History_DaysSummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string History_TotalSum {
            get {
                return ResourceManager.GetString("History_TotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Invites_ActivateButtonTitle {
            get {
                return ResourceManager.GetString("Invites_ActivateButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Invite.
        /// </summary>
        internal static string Invites_ActivatePageTitle {
            get {
                return ResourceManager.GetString("Invites_ActivatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate invite.
        /// </summary>
        internal static string Invites_ActivationError {
            get {
                return ResourceManager.GetString("Invites_ActivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Code.
        /// </summary>
        internal static string Invites_CodeLabel {
            get {
                return ResourceManager.GetString("Invites_CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invite.
        /// </summary>
        internal static string Invites_CreateInviteButtonText {
            get {
                return ResourceManager.GetString("Invites_CreateInviteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invite.
        /// </summary>
        internal static string Invites_CreateInvitePageTitle {
            get {
                return ResourceManager.GetString("Invites_CreateInvitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give this code to the employee.
        /// </summary>
        internal static string Invites_HelpTextForCode {
            get {
                return ResourceManager.GetString("Invites_HelpTextForCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Admin.
        /// </summary>
        internal static string Invites_IsAdmin {
            get {
                return ResourceManager.GetString("Invites_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving?.
        /// </summary>
        internal static string RideDetails_CancellationConfirmation {
            get {
                return ResourceManager.GetString("RideDetails_CancellationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this ride?.
        /// </summary>
        internal static string RideDetails_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("RideDetails_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string RideDetails_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("RideDetails_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost: .
        /// </summary>
        internal static string RideDetails_Cost {
            get {
                return ResourceManager.GetString("RideDetails_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  roubles.
        /// </summary>
        internal static string RideDetails_Currency {
            get {
                return ResourceManager.GetString("RideDetails_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RideDetails_DeleteButtonTitle {
            get {
                return ResourceManager.GetString("RideDetails_DeleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ride.
        /// </summary>
        internal static string RideDetails_PageTitle {
            get {
                return ResourceManager.GetString("RideDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per {0} minutes.
        /// </summary>
        internal static string RideDetails_Price {
            get {
                return ResourceManager.GetString("RideDetails_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration, minutes.
        /// </summary>
        internal static string RideDetails_RideDuration {
            get {
                return ResourceManager.GetString("RideDetails_RideDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        internal static string RideDetails_VehicleName {
            get {
                return ResourceManager.GetString("RideDetails_VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonTitle {
            get {
                return ResourceManager.GetString("SaveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignIn_Email {
            get {
                return ResourceManager.GetString("SignIn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string SignIn_FailedToLogin {
            get {
                return ResourceManager.GetString("SignIn_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have an account.
        /// </summary>
        internal static string SignIn_NoAccount {
            get {
                return ResourceManager.GetString("SignIn_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_PageTitle {
            get {
                return ResourceManager.GetString("SignIn_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_DoSignUp {
            get {
                return ResourceManager.GetString("SignUp_DoSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        internal static string SignUp_EmailIsEmpty {
            get {
                return ResourceManager.GetString("SignUp_EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        internal static string SignUp_InvalidEmail {
            get {
                return ResourceManager.GetString("SignUp_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_PageTitle {
            get {
                return ResourceManager.GetString("SignUp_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        internal static string SignUp_PasswordIsEmpty {
            get {
                return ResourceManager.GetString("SignUp_PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!.
        /// </summary>
        internal static string SignUp_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("SignUp_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string SignUp_RepeatPassword {
            get {
                return ResourceManager.GetString("SignUp_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        internal static string SignUp_WeakPassword {
            get {
                return ResourceManager.GetString("SignUp_WeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        internal static string Stats_CarName {
            get {
                return ResourceManager.GetString("Stats_CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Stats_Month {
            get {
                return ResourceManager.GetString("Stats_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats_PageTitle {
            get {
                return ResourceManager.GetString("Stats_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Stats_TotalCostPerPeriod {
            get {
                return ResourceManager.GetString("Stats_TotalCostPerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Stats_Week {
            get {
                return ResourceManager.GetString("Stats_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Stats_Year {
            get {
                return ResourceManager.GetString("Stats_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Vehicle_StartRide {
            get {
                return ResourceManager.GetString("Vehicle_StartRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Vehicle_StopRide {
            get {
                return ResourceManager.GetString("Vehicle_StopRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Vehicles_Delete {
            get {
                return ResourceManager.GetString("Vehicles_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this vehicle?.
        /// </summary>
        internal static string Vehicles_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("Vehicles_DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vehicle.
        /// </summary>
        internal static string Vehicles_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("Vehicles_DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details.
        /// </summary>
        internal static string Vehicles_DetailsPageTitle {
            get {
                return ResourceManager.GetString("Vehicles_DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open History.
        /// </summary>
        internal static string Vehicles_GoToHistory {
            get {
                return ResourceManager.GetString("Vehicles_GoToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string Vehicles_ListPageTitle {
            get {
                return ResourceManager.GetString("Vehicles_ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per {0} minutes.
        /// </summary>
        internal static string Vehicles_Price {
            get {
                return ResourceManager.GetString("Vehicles_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick save buttons.
        /// </summary>
        internal static string Vehicles_QuickSaveButtonsLabel {
            get {
                return ResourceManager.GetString("Vehicles_QuickSaveButtonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride saved.
        /// </summary>
        internal static string Vehicles_RideSaved {
            get {
                return ResourceManager.GetString("Vehicles_RideSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Vehicles_Save {
            get {
                return ResourceManager.GetString("Vehicles_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of time.
        /// </summary>
        internal static string Vehicles_UnitOfTime {
            get {
                return ResourceManager.GetString("Vehicles_UnitOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        internal static string Vehicles_VehicleName {
            get {
                return ResourceManager.GetString("Vehicles_VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
